import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Eye, Pencil, Plus, Search, Users, X } from 'lucide-react'
import { useAuth } from '../../context/useAuth'
import { saveGuest, searchGuests } from '../../services/guests/guestsService'
import type { Guest } from '../../types/guests'

type Draft = Omit<Guest, 'id' | 'searchName'>
const empty: Draft = { firstName: '', lastName: '', documentType: 'passport', documentNumber: '', nationality: '', birthDate: null, whatsapp: '', email: null, occupation: null, previousCity: null, nextCity: null, emergencyContact: null, notes: null }
const toDraft = (guest: Guest): Draft => ({ firstName: guest.firstName, lastName: guest.lastName, documentType: guest.documentType, documentNumber: guest.documentNumber, nationality: guest.nationality, birthDate: guest.birthDate, whatsapp: guest.whatsapp, email: guest.email, occupation: guest.occupation, previousCity: guest.previousCity, nextCity: guest.nextCity, emergencyContact: guest.emergencyContact, notes: guest.notes })

export function GuestsPage() {
  const { session } = useAuth(); const establishmentId = session?.establishmentId
  const [guests, setGuests] = useState<Guest[]>([]); const [term, setTerm] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [editor, setEditor] = useState<{ id?: string; draft: Draft } | null>(null); const [detail, setDetail] = useState<Guest | null>(null)
  const load = useCallback(async (value = term) => { if (!establishmentId) return; setLoading(true); try { setGuests(await searchGuests(establishmentId, value)) } catch { setError('No se pudieron cargar los huéspedes.')} finally { setLoading(false) } }, [establishmentId, term])
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer) }, [load])
  if (!establishmentId) return <div className="empty-state"><Users size={24} /><h1>Cuenta sin establecimiento</h1></div>
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editor) return; try { await saveGuest(establishmentId, editor.draft, editor.id); setEditor(null); await load('') } catch { setError('No se pudo guardar el huésped. Verifica tus permisos.') } }
  return <div className="dashboard-page guests-page"><header className="page-header"><div><span className="kicker">Base de huéspedes</span><h1>Huéspedes</h1><p>Encuentra perfiles rápido y conserva la información de cada viajero.</p></div><button className="primary-button compact-button" type="button" onClick={() => setEditor({ draft: empty })}><Plus size={18} />Nuevo huésped</button></header><div className="guest-toolbar"><Search size={18} /><input value={term} onChange={(event) => setTerm(event.target.value)} placeholder="Buscar por nombre..." aria-label="Buscar huéspedes" /></div>{error && <div className="form-error">{error}</div>}{loading ? <div className="screen-state inline-state"><span className="loader" />Buscando huéspedes...</div> : guests.length === 0 ? <div className="empty-state compact"><Users size={24} /><h2>No hay huéspedes</h2><p>Prueba otra búsqueda o registra el primer perfil.</p></div> : <div className="guest-list">{guests.map((guest) => <article className="guest-row" key={guest.id}><div className="guest-avatar">{guest.firstName[0]}{guest.lastName[0]}</div><div className="guest-name"><strong>{guest.firstName} {guest.lastName}</strong><small>{guest.nationality || 'Nacionalidad no registrada'} · {guest.whatsapp || guest.email || 'Sin contacto'}</small></div><button type="button" title="Ver detalle" onClick={() => setDetail(guest)}><Eye size={16} /></button><button type="button" title="Editar huésped" onClick={() => setEditor({ id: guest.id, draft: toDraft(guest) })}><Pencil size={16} /></button></article>)}</div>}{editor && <GuestModal editor={editor} onChange={setEditor} onClose={() => setEditor(null)} onSubmit={submit} />}{detail && <Detail guest={detail} onClose={() => setDetail(null)} />}</div>
}
function GuestModal({ editor, onChange, onClose, onSubmit }: { editor: { id?: string; draft: Draft }; onChange: (value: { id?: string; draft: Draft }) => void; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const d = editor.draft; const field = (key: keyof Draft) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => onChange({ ...editor, draft: { ...d, [key]: event.target.value } }); return <div className="modal-backdrop"><form className="modal-form guest-modal" onSubmit={onSubmit}><div className="modal-header"><div><span className="kicker">Registro</span><h2>{editor.id ? 'Editar huésped' : 'Nuevo huésped'}</h2></div><button type="button" onClick={onClose}><X size={19} /></button></div><div className="form-row"><label>Nombre<input value={d.firstName} onChange={field('firstName')} required /></label><label>Apellido<input value={d.lastName} onChange={field('lastName')} required /></label></div><div className="form-row"><label>Documento<select value={d.documentType} onChange={field('documentType')}><option value="passport">Pasaporte</option><option value="national_id">Cédula</option></select></label><label>Número<input value={d.documentNumber} onChange={field('documentNumber')} /></label></div><div className="form-row"><label>Nacionalidad<input value={d.nationality} onChange={field('nationality')} /></label><label>WhatsApp<input value={d.whatsapp} onChange={field('whatsapp')} /></label></div><div className="form-row"><label>Email<input type="email" value={d.email ?? ''} onChange={field('email')} /></label><label>Ciudad anterior<input value={d.previousCity ?? ''} onChange={field('previousCity')} /></label></div><div className="form-row"><label>Siguiente destino<input value={d.nextCity ?? ''} onChange={field('nextCity')} /></label><label>Contacto emergencia<input value={d.emergencyContact ?? ''} onChange={field('emergencyContact')} /></label></div><label>Notas<textarea value={d.notes ?? ''} onChange={field('notes')} rows={3} /></label><div className="modal-actions"><button className="secondary-button" type="button" onClick={onClose}>Cancelar</button><button className="primary-button" type="submit">Guardar</button></div></form></div> }
function Detail({ guest, onClose }: { guest: Guest; onClose: () => void }) { return <div className="modal-backdrop"><div className="modal-form bed-detail"><div className="modal-header"><div><span className="kicker">Perfil de huésped</span><h2>{guest.firstName} {guest.lastName}</h2></div><button type="button" onClick={onClose}><X size={19} /></button></div><p><strong>Documento:</strong> {guest.documentType} {guest.documentNumber || 'sin número'}</p><p><strong>Contacto:</strong> {guest.whatsapp || guest.email || 'No registrado'}</p><p><strong>Ruta:</strong> {guest.previousCity || 'sin ciudad anterior'} → {guest.nextCity || 'sin destino'}</p><p><strong>Emergencia:</strong> {guest.emergencyContact || 'No registrado'}</p><p><strong>Notas:</strong> {guest.notes || 'Sin notas'}</p></div></div> }
