export interface Currency {
  code: string;
  name: string;
}

export const CURRENCIES: Currency[] = [
  { code: 'BOB', name: 'Boliviano' },
  { code: 'USD', name: 'Dólar estadounidense' },
  { code: 'ARS', name: 'Peso argentino' },
  { code: 'BRL', name: 'Real brasileño' },
  { code: 'CLP', name: 'Peso chileno' },
  { code: 'PEN', name: 'Sol peruano' },
  { code: 'UYU', name: 'Peso uruguayo' },
  { code: 'PYG', name: 'Guaraní paraguayo' },
  { code: 'COP', name: 'Peso colombiano' },
  { code: 'VES', name: 'Bolívar venezolano' },
  { code: 'MXN', name: 'Peso mexicano' },
  { code: 'CRC', name: 'Colón costarricense' },
  { code: 'GTQ', name: 'Quetzal guatemalteco' },
  { code: 'HNL', name: 'Lempira hondureña' },
  { code: 'NIO', name: 'Córdoba nicaragüense' },
  { code: 'PAB', name: 'Balboa panameño' },
  { code: 'DOP', name: 'Peso dominicano' },
  { code: 'CUP', name: 'Peso cubano' },
  { code: 'JMD', name: 'Dólar jamaiquino' },
  { code: 'CAD', name: 'Dólar canadiense' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'Libra esterlina' },
  { code: 'CHF', name: 'Franco suizo' },
  { code: 'SEK', name: 'Corona sueca' },
  { code: 'NOK', name: 'Corona noruega' },
  { code: 'DKK', name: 'Corona danesa' },
  { code: 'PLN', name: 'Zloty polaco' },
  { code: 'CZK', name: 'Corona checa' },
  { code: 'HUF', name: 'Forinto húngaro' },
  { code: 'RON', name: 'Leu rumano' },
  { code: 'JPY', name: 'Yen japonés' },
  { code: 'CNY', name: 'Yuan chino' },
  { code: 'KRW', name: 'Won surcoreano' },
  { code: 'INR', name: 'Rupia india' },
  { code: 'THB', name: 'Baht tailandés' },
  { code: 'SGD', name: 'Dólar de Singapur' },
  { code: 'HKD', name: 'Dólar de Hong Kong' },
  { code: 'MYR', name: 'Ringgit malasio' },
  { code: 'IDR', name: 'Rupia indonesia' },
  { code: 'PHP', name: 'Peso filipino' },
  { code: 'VND', name: 'Dong vietnamita' },
  { code: 'AUD', name: 'Dólar australiano' },
  { code: 'NZD', name: 'Dólar neozelandés' },
  { code: 'AED', name: 'Dírham de Emiratos Árabes' },
  { code: 'ILS', name: 'Nuevo séquel israelí' },
  { code: 'SAR', name: 'Riyal saudí' },
  { code: 'QAR', name: 'Riyal catarí' },
  { code: 'TRY', name: 'Lira turca' },
  { code: 'ZAR', name: 'Rand sudafricano' },
  { code: 'EGP', name: 'Libra egipcia' },
  { code: 'MAD', name: 'Dírham marroquí' },
  { code: 'KES', name: 'Chelín keniano' },
];
